name: Merge conflict labeler

on:
  push:
  pull_request_target:
    types:
      - synchronize

jobs:
  triage:
    runs-on: ubuntu-20.04
    if: github.repository == 'jellyfin/jellyfin-androidtv'
    steps:
      - uses: eps1lon/actions-label-merge-conflict@v2.0.1
        with:
          dirtyLabel: merge conflict
          repoToken: ${{ secrets.GH_TOKEN }}
